### PR TITLE
RFC: Extending`node-tcp-relay`

### PR DESCRIPTION
**Pull request by berstend**
Your probably don't want to merge this PR right away. :)

I'd like to facilitate an implementation-specific discussion on how to best extend `node-tcp-relay`.

My goal is to add a `--ssl` flag to [hypertunnel](https://github.com/berstend/hypertunnel/) that would enable optional [TLS termination](https://github.com/berstend/hypertunnel/issues/1) on the public relay server (useful when local http servers are tunneled). This would result in feature parity to localtunnel/ngrok, while still being a much more stable product due to not inspecting and rewriting http headers. :)

Right now `node-tcp-relay` is a little hard to extend, so I did the following:
- Additionally export all base classes
- Add support for passing an optional class to be used in all `create*` methods

This allows me to use derivations of your classes and implement new functionality (I've added examples in a separate commit, e.g. to demonstrate TLS termination on the server using this approach).

You mentioned [here](https://github.com/tewarid/node-tcp-relay/issues/3#issuecomment-272412308) that you're thinking about adding generic callbacks, so I'm not sure if my PR goes against the style you've envisioned for extended and hooking into the behaviour of `node-tcp-relay`.

My changes don't cause any differences in the public API interface, just making it easier to use modified classes as a developer.

Could you elaborate a little more on how you think `node-tcp-relay` could be best extended? :) I can update my PR accordingly as I want to make sure it reflects how you envision the development of this project and your personal preference.

### CODE REVIEW

**Comment by tewarid** [comment]
This is the best PR I've received so far 😄 

I see a couple of things here

1. TLS at internet/service port of relay server - I didn't add SSL/TLS earlier expecting it would be done by service running behind the relay client. Doing it at the relay server is now required for HTTPS to work properly, as browsers [require](https://tools.ietf.org/html/rfc6125) subject alternative names in certificates to have FQDN. I've raised #9 to track this.

2. Extending the core classes for custom requirements - I'm still trying to wrap my head around this. In #3 I was thinking along the lines of passing data buffers through a set of callbacks that can inspect and modify data as needed. I need to dedicate some time to hack on this.

**Comment by berstend** [comment]
> This is the best PR I've received so far 😄

Haha, thanks! :) 

I was curious to learn more about the internals of `node-tcp-relay` and added debug statements to a local fork while playing with it. I ended up drinking too much coffee and rewrote everything in ES6 while doing that (classes, fat arrows, splitting up modules & listeners) 😅:

https://github.com/berstend/hypertunnel/tree/master/packages/hypertunnel-tcp-relay

This was a fun exercise that helped me understand more about sockets and net internals in general. 

I don't think the approach I used in this PR to enable custom classes (passing them as parameter) is the best, anymore. What I ended up with is to [add them as instance members](https://github.com/berstend/hypertunnel/blob/master/packages/hypertunnel-tcp-relay/lib/server/RelayServer.js#L27-L28), which [allows for easy overloading ](https://github.com/berstend/hypertunnel/blob/master/packages/hypertunnel-tcp-relay/lib/server/TLSRelayServer.js#L10) when extending the respective class.

The last link is by the way the whole TLSRelayServer implementation, I'm quite happy with how clean and readable that turned out in the end.

I'm a little spoiled by the readability and expressiveness that ES6 adds, so I will probably continue to use my own fork from here on. :) I don't intend for it to compete with your project, and will continue to submit PRs when I find underlying bugs or come across a nifty feature.

Fun fact: I initially passed on all relay options when creating internet listeners as well, which caused everything to explode when using secrets. It took me 3 hours to figure out that I should not pass secrets to the internet listener 😅 

Thanks!

**Comment by tewarid** [comment]
> I'm a little spoiled by the readability and expressiveness that ES6 adds, so I will probably continue to use my own fork from here on. :) I don't intend for it to compete with your project, and will continue to submit PRs when I find underlying bugs or come across a nifty feature.

The ES6 implementation does look pretty clean. No worries about competing with this implementation. In fact, your mention of ES6 reminded me of another fork https://github.com/codefresh-io/nat-traversal, that I see supports tls at the internet port.

**Comment by berstend** [comment]
Oh wow, didn't see that one before 😅

**Comment by tewarid** [comment]
I'll close the pull request for now as I have added TLS support in a manner that does not change the current implementation in a significant manner.

**Pull request closed without merging**
